---
title: "SMARTX: Porewater pH"
author: "May 2025 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
output_dir: "To Be Reviewed/PDF"
---

\newpage

##Run Information 
```{r run information, include=TRUE}
cat("Run Information:  ") #lets you know what section you're in 
#set the run date & user name 
  sample_year <- "2025"
  sample_month <- "May"
  user <- "Victoria Ellis"

#identify the files you want to read in 
  #read in as a list to accommodate multiple runs in a month
  pH_file <- "Raw Data/SMARTX_pH_(May 610).csv"

# Define the file path for  file - check year and month 
  final_path <- "Processed Data/GCReW_SMARTX_Porewater_pH_202505.csv"

#record any notes about the run or anything other info here: 
  run_notes <- ""
  
  #Collection_Dates = "Raw Data/Sample_Collection_Dates_2024.csv"

  cat(run_notes)
```

##Setup
```{r setup, include=FALSE}

#let you know which section you are in 
cat("Setup")

#load/install packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  dplyr,
  purrr,
  ggplot2,
  ggpubr,
  tidyr,
  tidyverse,
  lubridate,
  tinytex,
  stringr,
  writexl,
  readr,
  readxl,
  purrr,
  tinytex,
  broom,
  here)

#Set up file path for metadata 
  #downloaded metadata csv - downloaded from Google drive as csv for this year
  #Raw_Metadata = "Raw Data/Sample_IDs_LTREB_SMARTX_2024.csv"
  #Raw_Metadata = "..GCReW/GCReW_Project_Treatment_Metadata.csv"

  Raw_Metadata = here(".." , "GCReW", "GCReW_Project_Treatment_Metadata.csv")
  

```

##Read in metadata and create similar sample IDs for matching to samples 
```{r pull in metadata for later, include=FALSE}

#read in the raw metadata file 
raw_metadata <- read.csv(Raw_Metadata)

#clean up columns in metadata file:
  #Pull out only SMARTX Rows 
  #Create a Sample_Name column to match the SEAL
metadata <- raw_metadata %>%
  filter(grepl("SMARTX", Project, ignore.case = TRUE)) %>%
  mutate(Sample_Name = Sample.ID) %>%
  mutate(Month = sample_month) %>%
  mutate(Year = sample_year) %>%
    rename(
    Sample_ID = Sample.ID,
  ) %>%
  select(-N_Treatment)

#create a column for C3 or C4 plants 
#metadata <- metadata %>%
#  mutate(
#    Nickname = case_when(
#      startsWith(as.character(Plot), "3") ~ "C3",
#      startsWith(as.character(Plot), "6") ~ "C3",
#      startsWith(as.character(Plot), "4") ~ "C4",
#      TRUE ~ NA_character_  # if other values exist
 #   )
#  )

#create a column for dominant plant communities  
#metadata <- metadata %>%
#  mutate(
 #   Community = case_when(
 #     startsWith(as.character(Plot), "3") ~ "SCAM",
  #    startsWith(as.character(Plot), "6") ~ "SCAM",
#      startsWith(as.character(Plot), "4") ~ "SPPA, DISP",
  #    TRUE ~ NA_character_  # if other values exist
 #   )
 # )

#Bring in the collection date and any field notes if relevant 
#collection_metadata <- read.csv(Collection_Dates)
  #then we will merge the collection date for SMARTX based on the project and the chambers 

## Import Data & Clean
```

```{r Import Data, include=FALSE}
cat("Import Data")

#set file path for data - in run info chunk 
path <- ("file path")

#Read in Raw Data 
data_pH <- map(pH_file, read.csv)

# Combining Files
df_combo <- bind_rows(data_pH)

# Select needed columns & rename 
df_all <- df_combo %>%
  mutate(Sample_Name = paste0(Plot, "-",Depth)) %>%
  mutate(Analysis_rundate = paste0(match(Month, month.name), "/", Day, "/", Year)) %>%
select(
         Sample_Name = Sample_Name,
         pH = pH, 
         Analysis_rundate = Analysis_rundate,
       )

#Checking column headers
head(df)




```


## Merge samples with Metadata & check all samples are present 
```{r check sample ids with metadata, echo=FALSE}

cat("Merge Samples with Metadata")

#check to see if all samples are present in the metadata 
all_present <- all(metadata$Sample_Name %in% df_all$Sample_Name)

if (all_present) {
  message("All sample IDs are present in data.")
} else {
  message("Some sample IDs are missing from data.")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(metadata$Sample_Name, df_all$Sample_Name)
  print(missing_ids)
}


#merge metadata with sample run data 
merged_data <- df_all %>%
  left_join(metadata, by = c("Sample_Name" = "Sample_Name"))

#might want to include a flag or something to see that all the samples are included? 

df_all_clean <- merged_data 

```

\newpage

## Visualize Data
```{r Visualize Data C3, fig.height=10, echo=FALSE}
cat("Visualize Data")

### Ammonia 
pH_forplot <- df_all_clean

#C3 plots
pH_forplot_C3 <- pH_forplot %>%
  filter(Nickname == "C3")

pH_forplot_C3$Depth_cm <- 
  as.numeric(pH_forplot_C3$Depth_cm)

#group the data for plotting
pH_forplot_C3 <- pH_forplot_C3 %>%
  group_by(Depth_cm) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup() %>%
  mutate(Treatment = ifelse(Temp_Treatment == 0, ifelse(CO2_Treatment == "Ambient", "0 C + aCO2", "0 C + eCO2"), ifelse(Temp_Treatment == 1.7, "1.7 C + aCO2", ifelse(Temp_Treatment == 3.4, "3.4 C + aCO2", ifelse(Temp_Treatment == 5.1, ifelse(CO2_Treatment == "Ambient", "5.1 C + aCO2", "5.1 C + eCO2"), NA)))))

#create plot
viz_pH_plot_C3 <- ggplot(data = pH_forplot_C3, aes(
  x = as.factor(Temp_Treatment),
  y = pH,
  fill = as.factor(Treatment),
  color = as.factor(Treatment)
)) +
  geom_bar(stat = "identity", position = position_dodge2(padding = 0.4, preserve = c("total", "single"), )) +
  facet_grid(as.numeric(Depth_cm) ~ ., scales = "free_x") +
  scale_fill_manual(
    values = c(
      "0 C + aCO2" = "blue",
      "1.7 C + aCO2" = "green",
      "3.4 C + aCO2" = "orange",
      "5.1 C + aCO2" = "red",
      "0 C + eCO2" = "white",
      "5.1 C + eCO2" = "white"
    ),
    name = "Treatment:",
    breaks = c("0 C + aCO2", "1.7 C + aCO2", "3.4 C + aCO2", "5.1 C + aCO2", "0 C + eCO2", "5.1 C + eCO2"),
    labels = c("0 C + aCO2", "1.7 C + aCO2", "3.4 C + aCO2", "5.1 C + aCO2", "0 C + eCO2", "5.1 C + eCO2")
  ) +
  scale_color_manual(
    values = c(
      "0 C + aCO2" = "blue",
      "1.7 C + aCO2" = "green",
      "3.4 C + aCO2" = "orange",
      "5.1 C + aCO2" = "red",
      "0 C + eCO2" = "blue",
      "5.1 C + eCO2" = "red"
    ),
    name = "Treatment:",
    breaks = c("0 C + aCO2", "1.7 C + aCO2", "3.4 C + aCO2", "5.1 C + aCO2", "0 C + eCO2", "5.1 C + eCO2"),
    labels = c("0 C + aCO2", "1.7 C + aCO2", "3.4 C + aCO2", "5.1 C + aCO2", "0 C + eCO2", "5.1 C + eCO2")
  ) +
  theme_classic() +
  labs(
    x = " ",
    y = "pH",
    title = "C3: Porewater pH",
    fill = "CO2 Treatment",
    color = "+Temp. (C)"
  ) +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8),
      legend.key = element_rect("black")
    ) + 
  coord_flip(ylim = c(5.5,7.1))
print(viz_pH_plot_C3)

```
\newpage
```{r Visualize Data C4, fig.height=10, echo=FALSE}
#C4 plots
pH_forplot_C4 <- pH_forplot %>%
  filter(Nickname == "C4")

pH_forplot_C4$Depth_cm <-
  as.numeric(pH_forplot_C4$Depth_cm)

#group the data for plotting
pH_forplot_C4 <- pH_forplot_C4 %>%
  group_by(Depth_cm) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup()

viz_pH_plot_C4 <- ggplot(data = pH_forplot_C4, aes(
  x = as.factor(Temp_Treatment),
  y = pH,
  fill = as.factor(Temp_Treatment)
)) +
  geom_bar(stat = "identity", position = position_dodge2(padding = 0.25, preserve = "single"), ) +
  facet_grid(as.numeric(Depth_cm) ~ ., scales = "free_x") +
  facet_grid(Depth_cm ~ ., scales = "free_x") +
  scale_fill_manual(values = c(
    "0" = "blue",
    "1.7" = "green",
    "3.4" = "orange",
    "5.1" = "red"
  )) +
  
  theme_classic() +
  labs(x = " ",
       y = "pH",
       title = "C4: Porewater pH",
       fill = "+Temp. (C)") +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    ),
    legend.key = element_rect("black")
    
  ) +
  coord_flip(ylim = c(5.5,7.1))
print(viz_pH_plot_C4) 

```
\newpage
```{r Visualize Data by Rep C3,  fig.height=8.5, echo=FALSE}

#get replicate value and treatment info
pH_forplot_C3 <- pH_forplot_C3 %>%
  mutate(Replicate = str_sub(Plot, 2, 2)) %>%
  mutate(Treatment1 = ifelse(
    Temp_Treatment == 0,
    ifelse(CO2_Treatment == "Ambient", "+ 0 C", "eCO2 + 0 C"),
    ifelse(
      Temp_Treatment == 1.7,
      "+ 1.7 C",
      ifelse(
        Temp_Treatment == 3.4,
        "+ 3.4 C",
        ifelse(
          Temp_Treatment == 5.1,
          ifelse(CO2_Treatment == "Ambient", "+ 5.1 C", "eCO2 + 5.1 C"),
          NA
        )
      )
    )
  ))

#ensure points are in correct order
pH_forplot_C3 <- pH_forplot_C3[order(pH_forplot_C3$Depth_cm), ]

#make plot
viz_pH_plot_C3_2 <- ggplot(data = pH_forplot_C3, 
                            aes(x = pH, y = Depth_cm, color = Replicate)) +
  geom_point(size = 3) +
  geom_path(linewidth = 1) +
  scale_color_manual(values = c(
    "1" = "#FFD500",
    "2" = "#00D0FF",
    "3" = "#FF0075"
  )) +
  facet_grid(factor(
    Treatment1,
    levels = c("eCO2 + 0 C", "+ 0 C", "+ 1.7 C", "+ 3.4 C", "+ 5.1 C", "eCO2 + 5.1 C")
  ) ~ ., scales = "free_x") +
  labs(x = "pH", 
       y = "Depth (cm)", 
       title = "C3: Porewater pH by Replicate") +
  scale_y_reverse(breaks = c(10, 20, 40, 80, 120),
                  limits = c(125, 5)) +
  xlim(5.7, 7.1) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  )

viz_pH_plot_C3_2

```
\newpage

```{r Visualize Data by Rep C4,  fig.height=5.7, echo=FALSE}

#get replicate value and treatment info
pH_forplot_C4 <- pH_forplot_C4 %>%
  mutate(Replicate = str_sub(Plot, 2, 2)) %>%
  mutate(Treatment1 = ifelse(
    Temp_Treatment == 0,
    ifelse(CO2_Treatment == "Ambient", "+ 0 C", "eCO2 + 0 C"),
    ifelse(
      Temp_Treatment == 1.7,
      "+ 1.7 C",
      ifelse(
        Temp_Treatment == 3.4,
        "+ 3.4 C",
        ifelse(
          Temp_Treatment == 5.1,
          ifelse(CO2_Treatment == "Ambient", "+ 5.1 C", "eCO2 + 5.1 C"),
          NA
        )
      )
    )
  ))

#make sure point are in correct order
pH_forplot_C4 <- pH_forplot_C4[order(pH_forplot_C4$Depth_cm), ]

#make plot
viz_pH_plot_C4_2 <- ggplot(data = pH_forplot_C4, 
                            aes(x = pH, y = Depth_cm, color = Replicate)) +
  geom_point(size = 3) +
  geom_path(linewidth = 1) +
  scale_color_manual(values = c(
    "4" = "#FFD500",
    "5" = "#00D0FF",
    "6" = "#FF0075"
  )) +
  facet_grid(factor(Treatment1, levels = c("+ 0 C", "+ 1.7 C", "+ 3.4 C", "+ 5.1 C")) ~
               ., scales = "free_x") +
  labs(x = "pH", 
       y = "Depth (cm)", 
       title = "C4: Porewater pH by Replicate") +
  scale_y_reverse(breaks = c(10, 20, 40, 80, 120),
                  limits = c(125, 5)) +
  xlim(5.7, 7.11) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  )

viz_pH_plot_C4_2

```

##Export Data
```{r, include=FALSE}
#pull out what we need

df_all_clean_cols <- df_all_clean %>%
  select(
    Site,
    Project,
    Year,
    Month,
    Community,
    Nickname,
    Plot,
    Depth_cm,
    CO2_Treatment,
    Temp_Treatment,
    pH,
    Analysis_rundate
  )

final_data_labeled <- df_all_clean_cols %>%
  mutate(
    Run_notes = run_notes,# new column with notes about the run 
    )

#Order Columns for Final Data Frame
All_Clean_Data <- final_data_labeled %>%
  select(
    Site,
    Project,
    Year,
    Month,
    Community,
    Nickname,
    Plot,
    Depth_cm,
    CO2_Treatment,
    Temp_Treatment,
    pH,
    Analysis_rundate,
    Run_notes
  )
#head(Samples1)

write.csv(All_Clean_Data, final_path)
```

