---
title: "CO2xNxPhrag: Porewater pH"
author: "May 2025 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
output_dir: "To Be Reviewed/PDF"
---

\newpage

##Run Information 
```{r run information, include=TRUE}
cat("Run Information:  ") #lets you know what section you're in 
#set the run date & user name 
  sample_year <- "2025"
  sample_month <- "May"
  user <- "Victoria Ellis"

#identify the files you want to read in 
  #read in as a list to accommodate multiple runs in a month
  pH_file <- "Raw Data/1_Phrag_pH_(May).csv"

# Define the file path for  file - check year and month 
  final_path <- "Processed Data/GCReW_CO2xNxPhrag_Porewater_pH_202505.csv"

#record any notes about the run or anything other info here: 
  run_notes <- ""
  
  #Collection_Dates = "Raw Data/Sample_Collection_Dates_2024.csv"

  cat(run_notes)
```

##Setup
```{r setup, include=FALSE}

#let you know which section you are in 
cat("Setup")

#load/install packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  dplyr,
  purrr,
  ggplot2,
  ggpubr,
  tidyr,
  tidyverse,
  lubridate,
  tinytex,
  stringr,
  writexl,
  readr,
  readxl,
  purrr,
  tinytex,
  broom,
  here,
  ggpattern)

#Set up file path for metadata 
  #downloaded metadata csv - downloaded from Google drive as csv for this year
  #Raw_Metadata = "Raw Data/Sample_IDs_LTREB_SMARTX_2024.csv"
  #Raw_Metadata = "..GCReW/GCReW_Project_Treatment_Metadata.csv"

  Raw_Metadata = here(".." , "GCReW", "GCReW_Project_Treatment_Metadata.csv")
  

```

##Read in metadata and create similar sample IDs for matching to samples 
```{r pull in metadata for later, include=FALSE}

#read in metadata

raw_metadata <- read.csv(Raw_Metadata)
#clean up columns in metadata file:
#Pull out only SMARTX Rows
#Create a Sample_Name column to match the SEAL
metadata <- raw_metadata %>%
  filter(grepl("Phrag", Nickname, ignore.case = TRUE)) %>%
  mutate(Sample_Name = paste0(Sample.ID)) %>%
  mutate(Month = sample_month) %>%
  mutate(Year = sample_year) %>%
  rename(
    Sample_ID = Sample.ID,
    Plot_Name = Plot,
  ) %>%
  select(-Temp_Treatment) %>%
  mutate(Treatment = ifelse(
    CO2_Treatment == "Elevated" &
      N_Treatment == "Amended",
    "eCO2_N",
    ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Ambient",
      "eCO2",
      ifelse(CO2_Treatment == "Ambient" &
               N_Treatment == "Amended"  , "N" , "Ambient")
    )
  ))

#Bring in the collection date and any field notes if relevant
#collection_metadata <- read.csv(Collection_Dates)
#then we will merge the collection date for SMARTX based on the project and the chambers

```

```{r Import Data, include=FALSE}
cat("Import Data")

#set file path for data - in run info chunk 
path <- ("file path")

#Read in Raw Data 
data_pH <- map(pH_file, read.csv)

# Combining Files
df_combo <- bind_rows(data_pH)

# Select needed columns & rename 
df_all <- df_combo %>%
  mutate(Sample_Name = paste0(Plot, "-",Depth)) %>%
  mutate(Analysis_rundate = paste0(match(Month, month.name), "/", Day, "/", Year)) %>%
select(
         Sample_Name = Sample_Name,
         pH = pH, 
         Analysis_rundate = Analysis_rundate,
       )

#Checking column headers
head(df)




```


## Merge samples with Metadata & check all samples are present 
```{r check sample ids with metadata, echo=FALSE}

cat("Merge Samples with Metadata")

#check to see if all samples are present in the metadata 
all_present <- all(metadata$Sample_Name %in% df_all$Sample_Name)

if (all_present) {
  message("All sample IDs are present in data.")
} else {
  message("Some sample IDs are missing from data.")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(metadata$Sample_Name, df_all$Sample_Name)
  print(missing_ids)
}


#merge metadata with sample run data 
merged_data <- df_all %>%
  left_join(metadata, by = c("Sample_Name" = "Sample_Name"))

#might want to include a flag or something to see that all the samples are included? 

df_all_clean <- merged_data 

```

\newpage

## Visualize Data
```{r Visualize Data, echo=FALSE}
cat("Visualize Data")

### Ammonia
pH_forplot <- df_all_clean

color1 <- c("P1", "P2", "P3", "P4")
color2 <- c("P5", "P6", "P7", "P8")
color3 <- c("P10", "P9", "P11", "P12")


pH_forplot <- pH_forplot %>%
  mutate(
    Treatment1 = ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Amended",
      "eCO2 & eN",
      ifelse(
        CO2_Treatment == "Elevated" &
          N_Treatment == "Ambient",
        "eCO2 & aN",
        ifelse(
          CO2_Treatment == "Ambient" &
            N_Treatment == "Amended"  ,
          "aCO2 & eN" ,
          "aCO2 & aN"
        )
      )
    )
  ) %>%
  mutate(Treatment = ifelse(
    SubPlot == "A",
    ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Amended",
      "eCO2_eN_Phrag",
      ifelse(
        CO2_Treatment == "Elevated" &
          N_Treatment == "Ambient",
        "eCO2_aN_Phrag",
        ifelse(
          CO2_Treatment == "Ambient" &
            N_Treatment == "Amended"  ,
          "aCO2_eN_Phrag" ,
          "aCO2_aN_Phrag"
        )
      )
    ),
    ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Amended",
      "eCO2_eN_Native",
      ifelse(
        CO2_Treatment == "Elevated" &
          N_Treatment == "Ambient",
        "eCO2_aN_Native",
        ifelse(
          CO2_Treatment == "Ambient" &
            N_Treatment == "Amended"  ,
          "aCO2_eN_Native" ,
          "aCO2_aN_Native"
        )
      )
    )
  ))  %>%
  mutate(CO2_Treatment = ifelse(CO2_Treatment == "Ambient", "aCO2", "eCO2"))  %>%
  mutate(N_Treatment = ifelse(N_Treatment == "Ambient", "aN", "eN")) %>%
  mutate(Plot = Plot_Name) %>%
  mutate(
    Plot_Color = case_when(
      Plot %in% color1 ~ "Color1",
      Plot %in% color2 ~ "Color2",
      Plot %in% color3 ~ "Color3"
    )
  )


pH_forplot <- pH_forplot[order(pH_forplot$Depth_cm), ]

viz_pH_plot_v2 <- ggplot(
  data = pH_forplot,
  aes(
    x = factor(as.factor(CO2_Treatment), levels = c("eCO2", "aCO2")),
    y = pH,
    fill = as.factor(Treatment),
    color = as.factor(Treatment),
    pattern = as.factor(Treatment)
  )
) +
  geom_bar_pattern(
    stat = "identity",
    position = position_dodge2(padding = 0.25, preserve = "single"),
    pattern_angle = 45,
    pattern_density = 0.1,
    pattern_spacing = 0.025,
    pattern_key_scale_factor = 0.6
  ) +
  facet_grid(Depth_cm ~ N_Treatment, scales = "fixed") +
  scale_fill_manual(
    values = c(
      "eCO2_eN_Phrag" = "#DB5461",
      "eCO2_aN_Phrag" = "#454ADE",
      "aCO2_eN_Phrag" = "white",
      "aCO2_aN_Phrag" = "white",
      "eCO2_eN_Native" = "#DB5461",
      "eCO2_aN_Native" = "#454ADE",
      "aCO2_eN_Native" = "white",
      "aCO2_aN_Native" = "white"
    ),
    name = "Treatment:",
    breaks = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    ),
    labels = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    )
    
  ) +
  scale_color_manual(
    values = c(
      "eCO2_eN_Phrag" = "#DB5461",
      "eCO2_aN_Phrag" = "#454ADE",
      "aCO2_eN_Phrag" = "#DB5461",
      "aCO2_aN_Phrag" = "#454ADE",
      "eCO2_eN_Native" = "#DB5461",
      "eCO2_aN_Native" = "#454ADE",
      "aCO2_eN_Native" = "#DB5461",
      "aCO2_aN_Native" = "#454ADE"
    ),
    name = "Treatment:",
    breaks = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    ),
    labels = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    )
    
  ) +
  scale_pattern_manual(
    values = c(
      "eCO2_eN_Phrag" = "stripe",
      "eCO2_aN_Phrag" = "stripe",
      "aCO2_eN_Phrag" = "stripe",
      "aCO2_aN_Phrag" = "stripe",
      "eCO2_eN_Native" = "none",
      "eCO2_aN_Native" = "none",
      "aCO2_eN_Native" = "none",
      "aCO2_aN_Native" = "none"
    ),
    name = "Treatment:",
    breaks = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    ),
    labels = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    )
  ) +
  theme_classic() +
  labs(
    x = " ",
    y = "pH",
    title = "CO2xNxPhrag: Porewater Methane",
    fill = "CO2 Treatment:",
    color = "N Treatment:",
    pattern = "Subplot:"
  ) +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  ) +
  coord_flip()
print(viz_pH_plot_v2)


```

```{r, echo = FALSE}
#make plot

pH_forplot <- pH_forplot %>% 
  mutate(SubPlot = ifelse(SubPlot == "A", "Phrag", "Native"))

viz_pH_plot_2 <- ggplot(data = pH_forplot, aes(x = pH, y = as.numeric(Depth_cm), color = Plot_Color, shape = SubPlot)) +
  geom_point(size = 3) +
  geom_path(linewidth = 1) +
  scale_color_manual(
    values = c(
      "Color1" = "#FFD500",
      "Color2" = "#00D0FF",
      "Color3" = "#FF0075"
   
    ),
    labels = c("1", "2", "3")
  ) +
  facet_grid(Treatment1 ~ ., scales = "fixed") +
  labs(
    x = "pH",
    y = "Depth (cm)",
    title = "CO2xNxPhrag: Porewater pH by Replicate",
    color = "Replicate"
  ) +
  scale_y_reverse(breaks = c(20, 40), limits = c(45, 15)) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  )

viz_pH_plot_2

```

##Export Data
```{r, include=FALSE}
#pull out what we need

df_all_clean_cols <- df_all_clean %>%
  select(
    Site,
    Project,
    Year,
    Month,
    Community,
    Nickname,
    Plot_Name,
    SubPlot,
    Depth_cm,
    CO2_Treatment,
    N_Treatment,
    pH,
    Analysis_rundate
  )

final_data_labeled <- df_all_clean_cols %>%
  mutate(
    Run_notes = run_notes,# new column with notes about the run 
    Plot = Plot_Name
    )

#Order Columns for Final Data Frame
All_Clean_Data <- final_data_labeled %>%
  select(
    Site,
    Project,
    Year,
    Month,
    Community,
    Nickname,
    Plot,
    SubPlot,
    Depth_cm,
    CO2_Treatment,
    N_Treatment,
    pH,
    Analysis_rundate,
    Run_notes
  )
#head(Samples1)

write.csv(All_Clean_Data, final_path)
```

