---
title: "GC_Collate_Data_CO2xNxPhrag"
author: "Brenden Blakley"
date: "2025-08-25"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(purrr)
library(ggpattern)

```

```{r , echo=FALSE}

CH4_processed_files <- c("Processed Data/GCReW_CO2xNxPhrag_Porewater_CH4_202507_1.csv", "Processed Data/GCReW_CO2xNxPhrag_Porewater_CH4_202507_2.csv")
data_CH4 <- map(CH4_processed_files, read.csv)

# Combining Files
df_combo <- bind_rows(data_CH4)
```

## Visualize Data
```{r Visualize Data, echo=FALSE}
cat("Visualize Data")

### Ammonia
CH4_forplot <- df_combo

color1 <- c("P1", "P2", "P3", "P4")
color2 <- c("P5", "P6", "P7", "P8")
color3 <- c("P10", "P9", "P11", "P12")


CH4_forplot <- CH4_forplot %>%
  mutate(
    Treatment1 = ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Amended",
      "eCO2 & eN",
      ifelse(
        CO2_Treatment == "Elevated" &
          N_Treatment == "Ambient",
        "eCO2 & aN",
        ifelse(
          CO2_Treatment == "Ambient" &
            N_Treatment == "Amended"  ,
          "aCO2 & eN" ,
          "aCO2 & aN"
        )
      )
    )
  ) %>%
  mutate(Treatment = ifelse(
    SubPlot == "A",
    ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Amended",
      "eCO2_eN_Phrag",
      ifelse(
        CO2_Treatment == "Elevated" &
          N_Treatment == "Ambient",
        "eCO2_aN_Phrag",
        ifelse(
          CO2_Treatment == "Ambient" &
            N_Treatment == "Amended"  ,
          "aCO2_eN_Phrag" ,
          "aCO2_aN_Phrag"
        )
      )
    ),
    ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Amended",
      "eCO2_eN_Native",
      ifelse(
        CO2_Treatment == "Elevated" &
          N_Treatment == "Ambient",
        "eCO2_aN_Native",
        ifelse(
          CO2_Treatment == "Ambient" &
            N_Treatment == "Amended"  ,
          "aCO2_eN_Native" ,
          "aCO2_aN_Native"
        )
      )
    )
  ))  %>%
  mutate(CO2_Treatment = ifelse(CO2_Treatment == "Ambient", "aCO2", "eCO2"))  %>%
  mutate(N_Treatment = ifelse(N_Treatment == "Ambient", "aN", "eN")) %>%
  mutate(
    Plot_Color = case_when(
      Plot %in% color1 ~ "Color1",
      Plot %in% color2 ~ "Color2",
      Plot %in% color3 ~ "Color3"
    )
  )


CH4_forplot <- CH4_forplot[order(CH4_forplot$Depth_cm), ]

viz_CH4_plot_v2 <- ggplot(
  data = CH4_forplot,
  aes(
    x = factor(as.factor(CO2_Treatment), levels = c("eCO2", "aCO2")),
    y = CH4_Conc_uM,
    fill = as.factor(Treatment),
    color = as.factor(Treatment),
    pattern = as.factor(Treatment)
  )
) +
  geom_bar_pattern(
    stat = "identity",
    position = position_dodge2(padding = 0.25, preserve = "single"),
    pattern_angle = 45,
    pattern_density = 0.1,
    pattern_spacing = 0.025,
    pattern_key_scale_factor = 0.6
  ) +
  facet_grid(Depth_cm ~ N_Treatment, scales = "fixed") +
  scale_fill_manual(
    values = c(
      "eCO2_eN_Phrag" = "#DB5461",
      "eCO2_aN_Phrag" = "#454ADE",
      "aCO2_eN_Phrag" = "white",
      "aCO2_aN_Phrag" = "white",
      "eCO2_eN_Native" = "#DB5461",
      "eCO2_aN_Native" = "#454ADE",
      "aCO2_eN_Native" = "white",
      "aCO2_aN_Native" = "white"
    ),
    name = "Treatment:",
    breaks = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    ),
    labels = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    )
    
  ) +
  scale_color_manual(
    values = c(
      "eCO2_eN_Phrag" = "#DB5461",
      "eCO2_aN_Phrag" = "#454ADE",
      "aCO2_eN_Phrag" = "#DB5461",
      "aCO2_aN_Phrag" = "#454ADE",
      "eCO2_eN_Native" = "#DB5461",
      "eCO2_aN_Native" = "#454ADE",
      "aCO2_eN_Native" = "#DB5461",
      "aCO2_aN_Native" = "#454ADE"
    ),
    name = "Treatment:",
    breaks = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    ),
    labels = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    )
    
  ) +
  scale_pattern_manual(
    values = c(
      "eCO2_eN_Phrag" = "stripe",
      "eCO2_aN_Phrag" = "stripe",
      "aCO2_eN_Phrag" = "stripe",
      "aCO2_aN_Phrag" = "stripe",
      "eCO2_eN_Native" = "none",
      "eCO2_aN_Native" = "none",
      "aCO2_eN_Native" = "none",
      "aCO2_aN_Native" = "none"
    ),
    name = "Treatment:",
    breaks = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    ),
    labels = c(
      "eCO2_eN_Phrag",
      "eCO2_aN_Phrag",
      "aCO2_aN_Phrag",
      "aCO2_eN_Phrag",
      "eCO2_eN_Native",
      "eCO2_aN_Native",
      "aCO2_aN_Native",
      "aCO2_eN_Native"
    )
  ) +
  theme_classic() +
  labs(
    x = " ",
    y = "CH4 (uM)",
    title = "CO2xNxPhrag: Porewater Methane",
    fill = "CO2 Treatment:",
    color = "N Treatment:",
    pattern = "Subplot:"
  ) +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  ) +
  coord_flip()
print(viz_CH4_plot_v2)


```
```{r, echo = FALSE}
#make plot

CH4_forplot <- CH4_forplot %>% 
  mutate(SubPlot = ifelse(SubPlot == "A", "Phrag", "Native"))

viz_CH4_plot_2 <- ggplot(data = CH4_forplot, aes(x = CH4_Conc_uM, y = Depth_cm, color = Plot_Color, shape = SubPlot)) +
  geom_point(size = 3) +
  geom_path(linewidth = 1) +
  scale_color_manual(
    values = c(
      "Color1" = "#FFD500",
      "Color2" = "#00D0FF",
      "Color3" = "#FF0075"
   
    ),
    labels = c("1", "2", "3")
  ) +
  facet_grid(Treatment1 ~ ., scales = "fixed") +
  labs(
    x = "CH4 (uM)",
    y = "Depth (cm)",
    title = "CO2xNxPhrag: Porewater CH4 by Replicate",
    color = "Replicate"
  ) +
  scale_y_reverse(breaks = c(20, 40), limits = c(45, 15)) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  )

viz_CH4_plot_2
```

