---
title: "GC_Collate_Data"
author: "Brenden Blakley"
date: "2025-08-25"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(purrr)

```

```{r , echo=FALSE}

CH4_processed_files <- c("Processed Data/GCReW_CO2xNxPhrag_Porewater_CH4_202507_1.csv", "Processed Data/GCReW_CO2xNxPhrag_Porewater_CH4_202507_2.csv")
data_CH4 <- map(CH4_processed_files, read.csv)

# Combining Files
df_combo <- bind_rows(data_CH4)
```

## Visualize Data
```{r Visualize Data, echo=FALSE}
cat("Visualize Data")

### Ammonia 
CH4_forplot <- df_combo

#need to work out how best to plot these data 

viz_CH4_plot <- ggplot(data = CH4_forplot, aes(
  x = as.factor(CO2_Treatment),
  y = CH4_Conc_uM,
  fill = as.factor(CO2_Treatment)
)) +
  geom_bar(
    stat = "identity",
    position = position_dodge2(preserve = "single"),
    color = "black"
  ) +
  facet_grid(N_Treatment ~ Depth_cm, scales = "free_x") +
  scale_fill_manual(values = c(
    "Ambient" = "midnightblue",
    "Elevated" = "mediumvioletred"
  )) +
  theme_classic() +
  labs(x = " ",
       y = "CH4 (umol/L)",
       title = "CO2xN: Porewater Methane",
       fill = "Treatment:") +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  )
print(viz_CH4_plot) 


```
