---
title: "2-CO2xN Derived Non-Sedge Shoot Biomass 2005-2025"
output: html_document
date: "2026-01-07"
---

```{r}

# This program calculates the annual peak biomass of the non-sedge C4 grass Spartina patens (Aiton) Muhl. and Distichlis spicata (L.) Greene. They are from an experiment that began in 2005 in which the air CO2 concentration was increased and N was fertilized. The program ingests data from the file that has stem count and dry weight from each clipped plot. This file is used to calculate the area based dry mass for C4 grass and litter. Contact Pat Megonigal for details.

# Updated 2/13/2025 to only run current year data and append to previous years data

# install.packages("readr")
# install.packages("tidyverse")
library(readr)
library(tidyverse)
# These lines of code download any required packages for the code to function.

# set year & previous year
year=2025
previous_year=2024
# throughout this code, when importing .csv files you will need to manually add in the (published XX-XX-XXX) date as this changes each

# DO NOT MOVE PREVIOUS YEAR FILES TO 'RETIRED' FOLDER UNTIL THIS CODE HAS BEEN RUN

```

```{r}

# Import the data
SPbiomass_allyears <- read.csv(paste0('S:/Biogeochemistry/GCREW/2-CO2xN Experiment/0-Curated Data/4-All Harvest Data/CO2xN Master Harvest 2005-',year,' (published 01-07-2026).csv'), header = TRUE, sep = ",")
# you will need to manually adjust the published date as this changes.

#Filter out current year
SPbiomass <- SPbiomass_allyears[SPbiomass_allyears$Year == year,]

# Sort the data
SPbiomass <- SPbiomass %>%
  arrange(Year, Chamber, InOut, CO2, Nitrogen, Treatment, Quadrat)

# Data manipulation
Biomass <- SPbiomass %>%
  mutate(SPCount = ifelse(SPCount == -99, NA, SPCount),
         SPTotalMass = ifelse(SPTotalMass == -99, NA, SPTotalMass),
         DICount = ifelse(DICount == -99, NA, DICount),
         DITotalMass = ifelse(DITotalMass == -99, NA, DITotalMass),
         LitterTotalMass = ifelse(LitterTotalMass == -99, NA, LitterTotalMass),
         SPmass_m2 = SPTotalMass / 0.0025,
         DImass_m2 = DITotalMass / 0.0025,
         LitterMass_m2 = LitterTotalMass / 0.0025,
         SPdensity_m2 = SPCount / 0.0025,
         DIdensity_m2 = DICount / 0.0025) %>%
  filter(InOut != 0)

# Sort and summarize
QuadraMass <- Biomass %>%
  group_by(Year, Chamber, CO2, Nitrogen, Treatment, Quadrat) %>%
  summarise(across(c(SPdensity_m2, SPmass_m2, DIdensity_m2, DImass_m2, LitterMass_m2), mean, na.rm = TRUE), .groups = 'drop')

# Chamber mass calculation
ChamberMass <- QuadraMass %>%
  group_by(Year, Chamber, CO2, Nitrogen, Treatment) %>%
  summarise(across(c(SPdensity_m2, SPmass_m2, DIdensity_m2, DImass_m2, LitterMass_m2), ~mean(.x, na.rm = TRUE)), .groups = 'drop')

# Final adjustments
AllNonSedge <- ChamberMass %>%
  mutate(SPdensity_m2 = ifelse(is.na(SPdensity_m2), -99, SPdensity_m2),
         SPmass_m2 = ifelse(is.na(SPmass_m2), -99, SPmass_m2),
         DIdensity_m2 = ifelse(is.na(DIdensity_m2), -99, DIdensity_m2),
         DImass_m2 = ifelse(is.na(DImass_m2), -99, DImass_m2),
         LitterMass_m2 = ifelse(is.na(LitterMass_m2), -99, LitterMass_m2))

#Read in data set from previous years
past_years <- read.csv(paste0('S:/Biogeochemistry/GCREW/2-CO2xN Experiment/0-Curated Data/1-Biomass (Derived)/2-CO2xN Non-Sedge Shoot Biomass 2005-',previous_year,'.csv'), header = TRUE, sep = ",")

#Append present year data to previous years
AllNonSedge_allyears <- rbind(past_years, AllNonSedge)

# Export the data
write.csv(AllNonSedge_allyears, paste0('S:/Biogeochemistry/GCREW/2-CO2xN Experiment/0-Curated Data/1-Biomass (Derived)/2-CO2xN Non-Sedge Shoot Biomass 2005-',year,'.csv'), row.names=FALSE)
```

