---
title: "GENX: Porewater pH"
author: "July 2026 Samples"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
output_dir: "To Be Reviewed/PDF"
---

\newpage

##Run Information 
```{r run information, include=TRUE}
cat("Run Information:  ") #lets you know what section you're in 
#set the run date & user name 
  sample_year <- "2026"
  sample_month <- "May"
  user <- "Brenden Blakley"

#identify the files you want to read in 
  #read in as a list to accommodate multiple runs in a month
  pH_file <- "Raw Data/GENX_pH_(July).csv"

# Define the file path for  file - check year and month 
  final_path <- "Processed Data/GCReW_GENX_Porewater_pH_202605.csv"

#record any notes about the run or anything other info here: 
  run_notes <- ""
  
  #Collection_Dates = "Raw Data/Sample_Collection_Dates_2024.csv"

  cat(run_notes)
```

##Setup
```{r setup, include=FALSE}

#let you know which section you are in 
cat("Setup")

#load/install packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  dplyr,
  purrr,
  ggplot2,
  ggpubr,
  tidyr,
  tidyverse,
  lubridate,
  tinytex,
  stringr,
  writexl,
  readr,
  readxl,
  purrr,
  tinytex,
  broom,
  here)

#Set up file path for metadata 
  #downloaded metadata csv - downloaded from Google drive as csv for this year
  #Raw_Metadata = "Raw Data/Sample_IDs_LTREB_SMARTX_2024.csv"
  #Raw_Metadata = "..GCReW/GCReW_Project_Treatment_Metadata.csv"

  Raw_Metadata = here(".." , "GCReW", "GCReW_Project_Treatment_Metadata.csv")
  

```

##Read in metadata and create similar sample IDs for matching to samples 
```{r pull in metadata for later, include=FALSE}

#read in the raw metadata file 
raw_metadata <- read.csv(Raw_Metadata)

#clean up columns in metadata file:
  #Pull out only SMARTX Rows 
  #Create a Sample_Name column to match the SEAL
metadata <- raw_metadata %>%
  filter(grepl("GENX", Project, ignore.case = TRUE)) %>%
  mutate(Sample_Name = Sample.ID) %>%
  mutate(Month = sample_month) %>%
  mutate(Year = sample_year) %>%
    rename(
    Sample_ID = Sample.ID,
  ) %>%
  select(-N_Treatment)


```

```{r Import Data, include=FALSE}
cat("Import Data")

#set file path for data - in run info chunk 
path <- ("file path")

#Read in Raw Data 
data_pH <- map(pH_file, read.csv)

# Combining Files
df_combo <- bind_rows(data_pH)

# Select needed columns & rename 
df_all <- df_combo %>%
  mutate(Sample_Name = paste0(Plot, "-",Depth)) %>%
  mutate(Analysis_rundate = paste0(match(Month, month.name), "/", Day, "/", Year)) %>%
select(
         Sample_Name = Sample_Name,
         pH = pH, 
         Analysis_rundate = Analysis_rundate,
       )

#Checking column headers




```


## Merge samples with Metadata & check all samples are present 
```{r check sample ids with metadata, echo=FALSE}

cat("Merge Samples with Metadata")

#check to see if all samples are present in the metadata 
all_present <- all(metadata$Sample_Name %in% df_all$Sample_Name)

if (all_present) {
  message("All sample IDs are present in data.")
} else {
  message("Some sample IDs are missing from data.")
  
  # Optional: Which ones are missing?
  missing_ids <- setdiff(metadata$Sample_Name, df_all$Sample_Name)
  print(missing_ids)
}


#merge metadata with sample run data 
merged_data <- df_all %>%
  left_join(metadata, by = c("Sample_Name" = "Sample_Name"))

#might want to include a flag or something to see that all the samples are included? 

df_all_clean <- merged_data 

```

\newpage

## Visualize Data
```{r Visualize Data, fig.height=10, echo=FALSE}
cat("Visualize Data")

### Ammonia 
pH_forplot <- df_all_clean

pH_forplot$Depth_cm <- 
  as.numeric(pH_forplot$Depth_cm)

#group the data for plotting
pH_forplot <- pH_forplot %>%
  group_by(Depth_cm) %>%
  mutate(row_num = factor(row_number())) %>%  # create row_num as factor per group
  ungroup() %>%
  mutate(Treatment = paste0("+", Temp_Treatment, " " ,"C")) %>% mutate(Chamber = factor(Plot, levels = c(
      "Ch1", "Ch2", "Ch3", "Ch4", "Ch5", "Ch6", "Ch7", "Ch8", "Ch9", "Ch10", "Ch11", "Ch12"))) %>% mutate(Depth1 = paste0(Depth_cm, " cm")) %>% mutate(Depth = factor(Depth1, levels = c("5 cm", "20 cm", "40 cm", "80 cm")))

#create plot
viz_pH_plot <- ggplot(data = pH_forplot, aes(
  x = as.factor(Chamber),
  y = pH,
  fill = as.factor(Chamber)
)) +
  geom_col(stat = "identity", 
           position = position_dodge2(padding = 0.1, 
                                      width = 0.5, 
                                      preserve =  "single" )) +
  facet_grid(Depth ~ ., 
             scales = "free_x") +
  scale_fill_manual(
    breaks = c(
       "Ch1", "Ch2", "Ch3", "Ch4", "Ch5", "Ch6", "Ch7", "Ch8", "Ch9", "Ch10", "Ch11", "Ch12"),
    values = c(
       "Ch1" = "blue4",
       "Ch2" = "blue3",
       "Ch3" = "turquoise4",
       "Ch4" = "lightseagreen",
       "Ch5" = "mediumseagreen",
       "Ch6" = "limegreen",
       "Ch7" = "yellowgreen",
       "Ch8" = "yellow2",
       "Ch9" = "darkgoldenrod2",
       "Ch10" = "darkorange2",
       "Ch11" = "orangered1",
       "Ch12" = "red2"),
    name = "Chamber:"
  ) +
  theme_classic() +
  labs(
    x = " ",
    y = "pH",
    title = "GENX: Porewater pH"
  ) +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE, limits = rev) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8),
      legend.key = element_rect("black"),
    legend.position = "none"
    ) + 
  coord_flip(ylim = c(5.5,7.1))
print(viz_pH_plot)

```
\newpage

\newpage
```{r Visualize Data by Rep,  fig.height=8.5, echo=FALSE}

#get replicate value and treatment info
pH_forplot <- pH_forplot %>%
  mutate(Chamber = case_when(
    Plot == "Ch1"  ~ "Chamber 1",
    Plot == "Ch2"  ~ "Chamber 2",
    Plot == "Ch3"  ~ "Chamber 3",
    Plot == "Ch4"  ~ "Chamber 4",
    Plot == "Ch5"  ~ "Chamber 5",
    Plot == "Ch6"  ~ "Chamber 6",
    Plot == "Ch7"  ~ "Chamber 7",
    Plot == "Ch8"  ~ "Chamber 8",
    Plot == "Ch9"  ~ "Chamber 9",
    Plot == "Ch10"  ~ "Chamber 10",
    Plot == "Ch11"  ~ "Chamber 11",
    Plot == "Ch12"  ~ "Chamber 12"
    
    
  )
           ) %>% mutate(Chamber = factor(levels = c(
             "Chamber 1",
             "Chamber 2",
             "Chamber 3",
             "Chamber 4",
             "Chamber 5",
             "Chamber 6",
             "Chamber 7",
             "Chamber 8",
             "Chamber 9",
             "Chamber 10",
             "Chamber 11",
             "Chamber 12"
           ), Chamber))

#make plot
viz_pH_plot_2 <- ggplot(data = pH_forplot, 
                            aes(x = pH, y = Depth_cm, color = Chamber)) +
  geom_point(size = 3) +
  geom_path(linewidth = 1) +
  scale_color_manual(breaks = c(
       "Ch1", "Ch2", "Ch3", "Ch4", "Ch5", "Ch6", "Ch7", "Ch8", "Ch9", "Ch10", "Ch11", "Ch12"),
    values = c(
       "Chamber 1" = "blue4",
       "Chamber 2" = "blue3",
       "Chamber 3" = "turquoise4",
       "Chamber 4" = "lightseagreen",
       "Chamber 5" = "mediumseagreen",
       "Chamber 6" = "limegreen",
       "Chamber 7" = "yellowgreen",
       "Chamber 8" = "yellow2",
       "Chamber 9" = "darkgoldenrod2",
       "Chamber 10" = "darkorange2",
       "Chamber 11" = "orangered1",
       "Chamber 12" = "red2"),
    name = "Chamber:") +
  facet_wrap(~Chamber, ncol = 3, nrow = 4, scales = "free_x") +
  labs(x = "pH", 
       y = "Depth (cm)", 
       title = "GENX: Porewater pH by Chamber") +
  scale_y_reverse(breaks = c(5, 20, 40, 80),
                  limits = c(85, 0)) +
  xlim(5.7, 7.1) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8),
      legend.position = "none"
    )


viz_pH_plot_2

```
\newpage


##Export Data
```{r, include=FALSE}
#pull out what we need

df_all_clean_cols <- df_all_clean %>%
  select(
    Site,
    Project,
    Year,
    Month,
    Community,
    Nickname,
    Plot,
    Depth_cm,
    CO2_Treatment,
    Temp_Treatment,
    pH,
    Analysis_rundate
  )

final_data_labeled <- df_all_clean_cols %>%
  mutate(
    Run_notes = run_notes,# new column with notes about the run 
    )

#Order Columns for Final Data Frame
All_Clean_Data <- final_data_labeled %>%
  select(
    Site,
    Project,
    Year,
    Month,
    Community,
    Nickname,
    Plot,
    Depth_cm,
    CO2_Treatment,
    Temp_Treatment,
    pH,
    Analysis_rundate,
    Run_notes
  )
#head(Samples1)

write.csv(All_Clean_Data, final_path)
```

