---
title: "1-CensusQAQC (CO2xComm)"
output: html_document
date: "2024-01-21"
---

```{r}
######################################################################################
############ PROGRAMS FOR ERROR CHECKING AND TRANSFERRING CENSUS DATA ###########
######################################################################################

# install.packages("readr")
# install.packages("tidyverse")
library(readr)
library(tidyverse)
# These lines of code download any required packages for the code to function.

# set year
year=2022

```


```{r}
######################################################################################
############ STEP 1 -- RUN QA/QC PROGRAMS FOR ERROR CHECKING CENSUS DATA #############
######################################################################################

# Read in Census data 
Census <- read.csv(paste0('S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/1-CO2xComm SC Census (Filled).csv'))%>%
  select(-Notes, -PassFail)

# Data cleaning and flagging
CensusQAQC <- Census %>%
  mutate(HFlag = ifelse(Total_Height < Green_Height, 1, 0),
         HFlag = ifelse(Total_Height > 223 | (Total_Height < 5 & Total_Height > 0), 1, HFlag),
         WFlag = ifelse(Width > 8.4 | (Width < 0.2 & Width > 0), 1, 0),
         ZFlag = ifelse(is.na(Total_Height) | is.na(Green_Height) | is.na(Width), 1, 0))
CensusQAQC <- subset(CensusQAQC, HFlag != 0 | WFlag != 0 | ZFlag != 0)

# Remove observations where Rep is 99
CensusQAQC <- CensusQAQC %>%
  filter(Rep != 99)

# Export the cleaned data
write.csv(CensusQAQC, paste0( 'S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/1-CensusQAQC Error Report.csv'))

```


```{r}
######################################################################################
############ STEP 2 -- RUN QA/QC PROGRAMS FOR ERROR CHECKING DENSITY DATA ############
######################################################################################

# Import Density CSV file
Density <- read.csv(paste0('S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/2-CO2xComm SC Density (Filled).csv')) %>%
  select(-Notes)

# Creating DensityQAQC dataset
DensityQAQC <- Density %>%
  mutate(QDFlag = ifelse(Stem_Count > 166, 1, 0),
         ZFlag = ifelse(is.na(Stem_Count), 1, 0)) 
DensityQAQC <- subset(DensityQAQC, QDFlag != 0 | ZFlag != 0)

# Export the DensityQAQC data
write.csv(DensityQAQC, paste0( 'S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/2-DensityQAQC Error Report.csv'))

```


```{r}
############################################################################
############ STEP 3 -- GENERATE CENSUS OUTPUT FILE FOR TRANSFER ############
############################################################################

# Importing the Census dataset
Census <- read.csv(paste0('S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/1-CO2xComm SC Census (Filled).csv')) %>%
  select(-Notes, -PassFail)

# Creating CensusTransfer dataset
CensusTransfer <- Census %>%
  filter(Rep != 99) %>%
  mutate(Miner = -99,
         Rust = -99,
         Flower = -99)

# Exporting the CensusTransfer dataset
write.csv(CensusTransfer %>% select(-Rep), paste0( 'S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/1-Census (for transfer).csv'))

```

```{r}
############################################################################
############ STEP 4 -- GENERATE DENSITY OUTPUT FILE FOR TRANSFER  ##########
############################################################################

# Read the dataset into R
Density <- read.csv(paste0('S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/2-CO2xComm SC Density (Filled).csv')) %>%
  select(-Notes)

# Apply Chamber Area
DensityTransfer <- Density %>%
  mutate(Chamber_Area = 0.53)

# Export the data to CSV
write.csv(DensityTransfer, paste0( 'S:/Biogeochemistry/GCREW/1-CO2xCommunity Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/2-Density (for transfer).csv'))

```


