---
title: "combine_datafiles"
author: "giessnerm"
date: '2024-06-11'
output: html_document
---

#info

```{r}
#packages
library(ggplot2)
library(dplyr)
library(data.table)
library(matrixStats)
library(gridExtra)
library(ggpubr)
library(grid)
library(stringr)
library(plater)
library(raster)
library(tidyverse)
```

```{r, echo=FALSE}
#set working directory
setwd("S:/GlobalChangeEco/porewater_r scripts & Data/Data")

#read in plates
plate1 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate1_Summary_Data.csv",show_col_types = FALSE)
plate1 <- plate1[,c(2:8)]
plate2 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate2_Summary_Data.csv",show_col_types = FALSE)
plate2 <- plate2[,c(2:8)]
plate3 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate3_Summary_Data.csv",show_col_types = FALSE)
plate3 <- plate3[,c(2:8)]
plate4 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate4_Summary_Data.csv",show_col_types = FALSE)
plate4 <- plate4[,c(2:8)]
plate5 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate5_Summary_Data.csv",show_col_types = FALSE)
plate5 <- plate5[,c(2:8)]
plate6 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate6_Summary_Data.csv",show_col_types = FALSE)
plate6 <- plate6[,c(2:8)]
plate7 <- read_csv("S:/GlobalChangeEco/porewater_r scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_20250527_H2S_plate7_Summary_Data.csv",show_col_types = FALSE)
plate7 <- plate7[,c(2:8)]

```
#combine plates 
```{r}
all_plate <- rbind(plate1, plate2, plate3, plate4, plate5, plate6, plate7)
head(all_plate)

high_cv<- subset(all_plate, H2S_cv_flag == "High CV")
H2S_DiluteRerun <- subset(all_plate, H2S_flag == "adl")
H2S_bdlrerun <- subset(all_plate,H2S_flag == "bdl")
H2S_bdlrerun <- subset(H2S_bdlrerun, !(Dilution == 1))

```
# export data
```{r}
# export data
#summary
write.csv(all_plate, file="S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_2025May_plate1-7_Summary_Data.csv")

#high CV
write.csv(high_cv, file="S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_2025May_plate1-7_HighCV_Data.csv")

#rerun higher dilution
write.csv(H2S_DiluteRerun, file="S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_2025May_plate1-7_NeedDilution_Data.csv")
#rerun lower dilution
write.csv(H2S_bdlrerun, file="S:/GlobalChangeEco/Porewater_R scripts & Data/Data/Sulfide Microplate/LTREB/2025 May Porewater/QAQC'd Data/LTREB_H2S_2025May_plate1-7_NoDilution_Data.csv")
```







