---
title: "3-HarvestQAQC (Phrag CO2xN)"
output: html_document
date: "2026-05-04"
---

```{r}
######################################################################################
###### 2025 PROGRAMS FOR ERROR CHECKING AND FILE PREPARATION OF HARVEST DATA #########
######################################################################################

# install.packages("readr")
# install.packages("tidyverse")
library(readr)
library(tidyverse)
# These lines of code download any required packages for the code to function.

# set year
year=2025

```

```{r}
######################################################################################
######### STEP 1 -- RUN QA/QC PROGRAMS FOR ERROR CHECKING C4 HARVEST DATA ############
######################################################################################
 
# Import the CSV file
Harvest <- read.csv(paste0('S:/Biogeochemistry/GCREW/3-PhragmitesxCO2xN Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/4-Phrag CO2xN Non Phrag Harvest (Filled).csv'))

HarvestQAQC <- Harvest
 
HarvestQAQC$SC_Count[HarvestQAQC$SC_Count == -99] <- NA
HarvestQAQC$SP_Count[HarvestQAQC$SP_Count == -99] <- NA
HarvestQAQC$DI_Count[HarvestQAQC$DI_Count == -99] <- NA
HarvestQAQC$SC_Mass[HarvestQAQC$SC_Mass == -99] <- NA
HarvestQAQC$SP_Mass[HarvestQAQC$SP_Total_Mass == -99] <- NA
HarvestQAQC$DI_Mass[HarvestQAQC$DI_Total_Mass == -99] <- NA
HarvestQAQC$AM_Count[HarvestQAQC$AM_Count == -99] <- NA
HarvestQAQC$AM_Mass[HarvestQAQC$AM_Mass == -99] <- NA
# Any -99 value is converted into NA.
# Note: SC_Mass versus SP_Total_Mass and DI_Total_Mass. Had to rename in code to match CSV column headings.

HarvestQAQC$SCCFlag1 <- ifelse(HarvestQAQC$SC_Count > 15, 1, 0)
HarvestQAQC$SPCFlag1 <- ifelse(HarvestQAQC$SP_Count > 58, 1, 0)
HarvestQAQC$DICFlag1 <- ifelse(HarvestQAQC$DI_Count > 31, 1, 0)
HarvestQAQC$AMCFlag1 <- ifelse(HarvestQAQC$AM_Count > 10, 1, 0)
# Count QAQC by Spp.

HarvestQAQC$SCMFlag <- ifelse(HarvestQAQC$SC_Mass > 10, 1, 0)
HarvestQAQC$SPMFlag <- ifelse(HarvestQAQC$SP_Mass > 8.9, 1, 0)
HarvestQAQC$DIMFlag <- ifelse(HarvestQAQC$DI_Mass > 5.1, 1, 0)
HarvestQAQC$AMMFlag <- ifelse(HarvestQAQC$AM_Mass > 3, 1, 0)
# Mass QAQC by Spp.
  
HarvestQAQC$SCCFlag2 <- ifelse(HarvestQAQC$SC_Count != 0 & HarvestQAQC$SC_Mass == 0, 1, 0)
HarvestQAQC$SPCFlag2 <- ifelse(HarvestQAQC$SP_Count != 0 & HarvestQAQC$SP_Mass == 0, 1, 0)
HarvestQAQC$DICFlag2 <- ifelse(HarvestQAQC$DI_Count != 0 & HarvestQAQC$DI_Mass == 0, 1, 0)
HarvestQAQC$AMCFlag2 <- ifelse(HarvestQAQC$AM_Count != 0 & HarvestQAQC$AM_Mass == 0, 1, 0)
# QAQC Check by Spp.
# If there is a count value but no mass value, the measurement is flagged.

HarvestQAQC$SCCFlag <- ifelse(HarvestQAQC$SCCFlag1 == 1 | HarvestQAQC$SCCFlag2 == 1, 1, 0)
HarvestQAQC$SPCFlag <- ifelse(HarvestQAQC$SPCFlag1 == 1 | HarvestQAQC$SPCFlag2 == 1, 1, 0)
HarvestQAQC$DICFlag <- ifelse(HarvestQAQC$DICFlag1 == 1 | HarvestQAQC$DICFlag2 == 1, 1, 0)
HarvestQAQC$AMCFlag <- ifelse(HarvestQAQC$AMCFlag1 == 1 | HarvestQAQC$AMCFlag2 == 1, 1, 0)
# Combined flags by Spp into one column.
  
HarvestQAQC$O1CFlag <- ifelse(HarvestQAQC$Other_1_Count > 35, 1, 0)
HarvestQAQC$O1MFlag <- ifelse(HarvestQAQC$Other_1_Mass > 11.9, 1, 0)
HarvestQAQC$O2CFlag <- ifelse(HarvestQAQC$Other_2_Count > 35, 1, 0)
HarvestQAQC$O2MFlag <- ifelse(HarvestQAQC$Other_2_Mass > 11.9, 1, 0)
# Other count and mass QAQC. 

HarvestQAQC$O1Flag1 <- ifelse(HarvestQAQC$Other_1_Species == 'none' & HarvestQAQC$Other_1_Count != 0, 1, 0)
HarvestQAQC$O1Flag2 <- ifelse(HarvestQAQC$Other_1_Species == 'none' & HarvestQAQC$Other_1_Mass != 0, 1, 0)
HarvestQAQC$O2Flag1 <- ifelse(HarvestQAQC$Other_2_Species == 'none' & HarvestQAQC$Other_2_Count != 0, 1, 0)
HarvestQAQC$O2Flag2 <- ifelse(HarvestQAQC$Other_2_Species == 'none' & HarvestQAQC$Other_2_Mass != 0, 1, 0)
# If "none" other species were listed and there is a count or mass value entered, the measurement is flagged.
  
HarvestQAQC$O1Flag <- ifelse(HarvestQAQC$O1Flag1 == 1 | HarvestQAQC$O1Flag2 == 1, 1, 0)
HarvestQAQC$O2Flag <- ifelse(HarvestQAQC$O2Flag1 == 1 | HarvestQAQC$O2Flag2 == 1, 1, 0)
# Combined other spp count and mass flags into one column.

HarvestQAQC <- subset(HarvestQAQC,selec = -c(SCCFlag1,SPCFlag1,DICFlag1,AMCFlag1, SCCFlag2,SPCFlag2,DICFlag2,AMCFlag2, O1Flag1,O1Flag2,O2Flag1,O2Flag2))
# Removed all columns that were combined into one flagged column.

HarvestQAQC <- subset(HarvestQAQC, O1Flag != 0 | O2Flag != 0 | SCCFlag != 0 | SPCFlag != 0 | DICFlag != 0 | AMCFlag != 0 |SCMFlag != 0 | SPMFlag != 0 | DIMFlag != 0 | AMCFlag != 0 | O1CFlag != 0 | O1MFlag != 0 | O2CFlag != 0 | O2MFlag != 0) 
# This step deletes measurements that have "0" in all of the flag columns, meaning there are no errors. Any measurement with a flag (signified by a "1" value in a flag column), are kept and listed in the HarvestQAQC Error Report. 

write.csv(HarvestQAQC, paste0( 'S:/Biogeochemistry/GCREW/3-PhragmitesxCO2xN Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/4-HarvestQAQC Error Report.csv'), row.names = FALSE)
# Exports the HarvestQAQC Error Report.csv to the Shared drive.

```

```{r}
#################################################################################
########### STEP 2 -- GENERATE C4 HARVEST OUTPUT FILE FOR TRANSFER ###############
#################################################################################

# Import the CSV file
Harvest <- read.csv(paste0('S:/Biogeochemistry/GCREW/3-PhragmitesxCO2xN Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/4-Phrag CO2xN Non Phrag Harvest (Filled).csv'))

# List of desired columns
desired_cols <- c("Year", "Chamber", "Quadrat", "In_Out", "CO2", "Nitrogen", "Treatment",
                  "SC_Allometry_Count", "Total_Height", "Green_Height", "Width", "SC_Allometry_Mass",
                  "SC_Count", "SC_Mass", "SP_Count", "SP_Mass", "DI_Count", "DI_Mass",
                  "AM_Count", "AM_Mass", "Other_1_Species", "Other_1_Count", "Other_1_Mass",
                  "Other_2_Species", "Other_2_Count", "Other_2_Mass", "Other_3_Species",
                  "Other_3_Count", "Other_3_Mass", "Litter_Mass")

# Identify missing columns
missing_cols <- setdiff(desired_cols, names(Harvest))

# Add missing columns with -99 & 'none' values
for (col in missing_cols) {
  Harvest[[col]] <- ifelse(col %in% c("Other_2_Species", "Other_3_Species"), "none", -99)
}

# Convert species columns to character BEFORE replacing values
Harvest <- Harvest %>%
  mutate(across(c("Other_1_Species", "Other_2_Species", "Other_3_Species"), 
                ~replace(.x, .x %in% c("0", 0, "NA", NA, ""), "none")))

  Harvest <- Harvest %>%
  mutate(across(c("SC_Allometry_Count", "Total_Height", "Green_Height", "Width", "SC_Allometry_Mass", "Litter_Mass"), ~ -99))

Harvest <- Harvest %>%
  mutate(
    across(c("Other_2_Count", "Other_2_Mass"), ~replace_na(as.numeric(.x), 0)),
    across(c("Other_3_Count", "Other_3_Mass"), ~replace(.x, .x == -99, 0))
  )

# Select the desired columns
HarvestTransfer <- Harvest %>% select(all_of(desired_cols))

# Exports the Harvest (for transfer).csv to the Shared drive.
write.csv(HarvestTransfer, paste0('S:/Biogeochemistry/GCREW/3-PhragmitesxCO2xN Experiment/1-Plant Biomass & CN Data/Shoot Biomass Data/',year,'/Data/4-Phrag Harvest (for transfer).csv'), row.names = FALSE)

```


