---
title: "Water Level checks"
author: "Selina Cheng"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "yeti"
---
  
Last modified January 06 2026 by Taylor Smith

```{r setup, include=FALSE}
# Get functions
if (!require("pacman")) install.packages("pacman")
pacman::p_load(knitr, tidyverse, data.table, lubridate, utils, ggpubr, plyr, gghighlight, kableExtra, geomtextpath, grid, Cairo)

# Create load data function
load_data<-function(dir, pattern){
  i2<-list.files(dir, pattern = pattern, all.files = TRUE,
                 full.names = TRUE, recursive = FALSE,
                 ignore.case = T)
  l2 <- lapply(i2, fread, sep=",", fill=TRUE, skip=1, header=TRUE)
  dt_raw <- rbindlist(l2, fill=TRUE, use.names=TRUE)
  dt_raw <- dt_raw %>%
    filter(TIMESTAMP != "TS" & TIMESTAMP != "")
  return(dt_raw)
}

# Set figure output dimensions
options(bitmapType="cairo")
knitr::opts_chunk$set(fig.width=15, fig.height=10, dpi = 150, echo = T, dev = "ragg_png")

```

```{r load data, echo=FALSE}

dir <- paste0(Sys.getenv("dropbox_filepath"), "GCREW_LOGGERNET_DATA/current_data", sep = "")

# Read in GENX Water level data
pattern <- "GENX_WaterlevelHydros"
dt_genx <- load_data(dir=dir, pattern=pattern)
dt_genx$logger <- "GENX"
dt_genx <- dt_genx %>%
  dplyr::mutate(H21_Depth = as.numeric(H21_Depth), H21_Depth = H21_Depth/10) %>%
  dplyr::rename(Depth = H21_Depth, Salinity = Derived_Salinity, Temperature = H21_Temperature)

# Read in C3LOG water level data
pattern <- "C3LOG_WaterLevel"
dt_c3 <- load_data(dir = dir, pattern = pattern)
dt_c3$logger <- "C3LOG"

# Read in C4LOG water level data
pattern <- "C4LOG_WaterLevel"
dt_c4 <- load_data(dir = dir, pattern = pattern)
dt_c4$logger <- "C4LOG"

# Read in GCREW MET water level data
pattern <- "GCREW_MET_GCREW_Waterlevel200"
dt_gcrewmet <- load_data(dir = dir, pattern = pattern)
dt_gcrewmet$logger <- "GCREW_MET"

# Bind all together
dt_waterlevel <- do.call("rbind.fill", list(dt_c3, dt_c4, dt_gcrewmet, dt_genx))

# Format timestamp
dt_waterlevel$TIMESTAMP <- as.POSIXct(dt_waterlevel$TIMESTAMP, format = "%Y-%m-%d %H:%M:%S", tz= "America/Jamaica")

# This chunk just selects the last day's worth of data
# But generally select 1-2 day's worth of data
# You may have to code a date selection manually
yesterday <- format(Sys.Date()-2,"%Y-%m-%d %H:%M:%S")

dt_waterlevel2 <- dt_waterlevel %>%
  filter(TIMESTAMP >= yesterday)

# Choose just the columns we want
dt_waterlevel2 <- dt_waterlevel2 %>%
  select(TIMESTAMP, Depth, Temperature, Salinity, logger) %>%
  mutate(Depth = as.numeric(Depth),
         Temperature = as.numeric(Temperature),
         Salinity = as.numeric(Salinity))

```

### **Are any Aquatroll depth sensors down?**

```{r any NAs, echo=FALSE}
# Make data frame wider
dt_wide <- pivot_wider(dt_waterlevel2, id_cols = "TIMESTAMP", names_from  = "logger", values_from = "Depth")

# Get number of nas
num_nas <- as.data.frame(sapply(dt_wide, function(x)sum(is.na(x))))

num_nas$parameter <- row.names(num_nas)
num_nas$parameter <- paste0(num_nas$parameter, "_depth")

names(num_nas) <- c("num_nas", "parameter")

row.names(num_nas) <- NULL

# Order number of NAs so that plots with the most NAs come up on top
num_nas <- num_nas[order(num_nas$num_nas, decreasing = T),]
num_nas$percent_nas <- round((num_nas$num_nas / nrow(dt_wide) * 100), digits = 2)

num_nas <- num_nas %>%
  filter(!grepl("TIMESTAMP", parameter)) %>%
  select(parameter, num_nas, percent_nas)

# Print table
knitr::kable(num_nas, row.names = F, table.attr = "style='width:45%;'") %>%
  kable_styling("striped")
```

### **Plot all Aquatroll depths together**

```{r plot together, echo = F, cache = F}
dt_waterlevel2 %>%
  ggplot(aes(x = TIMESTAMP, y = Depth, colour = logger))+
  geom_point(na.rm = T, size = 2)+
  theme(legend.title=element_blank()) +
  labs(x = "Timestamp", y = "Depth (cm)")+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))+
  theme(legend.title=element_blank())+
  theme(legend.text = element_text(size=24)) + 
  guides(colour = guide_legend(override.aes = list(size=7)))

```

### **Aquatroll depths with offset**

```{r plot with offsets, echo = F, cache = F}
# Add offset column
dt_waterlevel2 <- dt_waterlevel2 %>%
  mutate(corrected_depth = case_when(logger == "C3LOG" ~ (Depth-45),
                                     logger == "C4LOG" ~ (Depth-65),
                                     logger == "GCREW_MET" ~ (Depth-58),
                                     logger == "GENX" ~ (Depth-76)))

dt_waterlevel2 %>%
  ggplot(aes(x = TIMESTAMP, y = corrected_depth, colour = logger))+
  geom_point(na.rm = T, size = 2)+
  theme(legend.title=element_blank()) +
  labs(x = "Timestamp", y = "Depth (cm)")+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))+
  theme(legend.title=element_blank())+
  theme(legend.text = element_text(size=24)) + 
  guides(colour = guide_legend(override.aes = list(size=7)))

```

### **Plot all salinity together**
```{r plot together2, echo = F, cache = F}
dt_waterlevel2 %>%
  ggplot(aes(x = TIMESTAMP, y = Salinity, colour = logger))+
  geom_point(na.rm = T, size = 2)+
  theme(legend.title=element_blank()) +
  labs(x = "Timestamp", y = "Salinity (ppt)")+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))+
  theme(legend.title=element_blank())+
  theme(legend.text = element_text(size=24)) + 
  guides(colour = guide_legend(override.aes = list(size=7)))

```

### **Plot all water temperature together**
```{r plot together3, echo = F, cache = F}
dt_waterlevel2 %>%
  ggplot(aes(x = TIMESTAMP, y = Temperature, colour = logger))+
  geom_point(na.rm = T, size = 2)+
  theme(legend.title=element_blank()) +
  labs(x = "Timestamp", y = expression("Water Temperature " (degree~C)))+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))+
  theme(legend.title=element_blank())+
  theme(legend.text = element_text(size=24)) + 
  guides(colour = guide_legend(override.aes = list(size=7)))

```

### **Depths at individual loggers are plotted below.**

### **C3LOG depth**

```{r c3log depth, echo = F, cache = F}
dt_waterlevel2 %>%
filter(logger == "C3LOG") %>%
ggplot(aes(x = TIMESTAMP, y = Depth)) +
geom_point(na.rm = T, size = 2) +
labs(x = "Timestamp", y = "Depth (cm)")+
theme_light()+
theme(axis.title.x = element_text(size = 23, face = "bold"),
     axis.title.y = element_text(size=23, face = "bold"),
     axis.text.x = element_text(size=23, face = "bold"),
     axis.text.y = element_text(size=23, face = "bold"))

```

### **GCREW MET depth**

```{r gcrew met depth, echo = F, cache = F}
dt_waterlevel2 %>%
  filter(logger == "GCREW_MET") %>%
  ggplot(aes(x = TIMESTAMP, y = Depth)) +
  geom_point(na.rm = T, size = 2) + 
  labs(x = "Timestamp", y = "Depth (cm)")+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))


```

### **GENX depth**

```{r genx depth, echo = F, cache = F}
dt_waterlevel2 %>%
  filter(logger == "GENX") %>%
  ggplot(aes(x = TIMESTAMP, y = Depth)) +
  geom_point(na.rm = T, size = 2) + 
  labs(x = "Timestamp", y = "Depth (cm)")+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))
```

### **C4LOG depth**

```{r c4log depth, echo = F, cache = F}
dt_waterlevel2 %>%
  filter(logger == "C4LOG") %>%
  ggplot(aes(x = TIMESTAMP, y = Depth)) +
  geom_point(na.rm = T, size = 2) + 
  labs(x = "Timestamp", y = "Depth (cm)")+
  theme_light()+
  theme(axis.title.x = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size=23, face = "bold"),
        axis.text.x = element_text(size=23, face = "bold"),
        axis.text.y = element_text(size=23, face = "bold"))


```


