---
title: "SMARTX_SO4_Cl_Compile"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r}

library(here)
library(dplyr)
library(ggplot2)
library(purrr)
library(data.table)
library(tidyverse)
```


```{r}

year <- "2025"

SO4_path <- "GCReW_SMARTX_PW_Processed_"

SO4_may1_dat <- read.csv(here("..", "GCREW","SMARTX", "Porewater", "Sulfate_Chloride", year, "Processed Data", paste0(SO4_path, "Cl_SO4_", year, "05", "_610-332", ".csv")))

SO4_july1_dat <- read.csv(here("..", "GCREW","SMARTX", "Porewater", "Sulfate_Chloride", year, "Processed Data", paste0(SO4_path, "Cl_SO4_",year, "07", "_610-332",".csv")))

SO4_sept1_dat <- read.csv(here("..", "GCREW","SMARTX", "Porewater", "Sulfate_Chloride", year, "Processed Data", paste0(SO4_path, "Cl_SO4_",year, "09","_610-332", ".csv")))

SO4_may2_dat <- read.csv(here("..", "GCREW","SMARTX", "Porewater", "Sulfate_Chloride", year, "Processed Data", paste0(SO4_path, "Cl_SO4_", year, "05","_333-463", ".csv")))

SO4_july2_dat <- read.csv(here("..", "GCREW","SMARTX", "Porewater", "Sulfate_Chloride", year, "Processed Data", paste0(SO4_path, "Cl_SO4_", year, "07","_333-463", ".csv")))

SO4_sept2_dat <- read.csv(here("..", "GCREW","SMARTX", "Porewater", "Sulfate_Chloride", year, "Processed Data", paste0(SO4_path, "Cl_SO4_",year, "09","_333-463", ".csv")))
```

```{r}
SO4_dat <- rbind(SO4_july1_dat[,-1], SO4_may1_dat[,-1], SO4_sept1_dat[,-1], SO4_july2_dat[,-1], SO4_may2_dat[,-1], SO4_sept2_dat[,-1])
```

```{r}
write.csv(SO4_dat, paste0("SMARTX_Porewater_SO4_Cl_", year, ".csv"))

```
