---
title: "GCReW_CO2xN_Porewater_Collation"
output: html_document
date: "2026-01-28"
---

```{r}
library(here)
library(dplyr)
library(ggplot2)
library(purrr)
library(data.table)
library(tidyverse)
```


##Read in Data
```{r}

year <- "2024"

path <- "CO2xN_Porewater_"

CH4_dat <- read.csv(here("..", "GCREW","CO2xN", "Porewater", "CH4", year, "Compiled_Data", paste0(path, "CH4_", year, ".csv")))
  
NH3_dat <- read.csv(here("..", "GCREW","CO2xN", "Porewater", "Ammonium", year, "Compiled_Data", paste0(path, "NH4_", year, ".csv"))) %>% mutate(Site = "GCReW", Project ="CO2xN", Community = "SCAM", Nickname = "2-Meter", N_Treatment = ifelse(Nitrogen == 0, "Amended", "Ambient"), CO2_Treatment = ifelse(Treatment == 1 | Treatment == 2, "Ambient", "Elevated"), Plot = sub("-.*", "", SampleID)) %>% select(-Treatment, -SampleID, -Nitrogen, -Chamber, -CO2) %>% rename(NH3_Conc_uM = NH4.uM, Depth_cm = Depth)
  
pH_dat <-  read.csv(here("..", "GCREW","CO2xN", "Porewater", "pH", year, "Compiled_Data", paste0(path, "pH_", year, ".csv"))) %>% mutate(Site = "GCReW", Project ="CO2xN", Community = "SCAM", Nickname = "2-Meter", N_Treatment = ifelse(Nitrogen == 0, "Amended", "Ambient"), CO2_Treatment = ifelse(Treatment == 1 | Treatment == 2, "Ambient", "Elevated"), Plot = sub("-.*", "", SampleID)) %>% select(-Treatment, -SampleID, -Nitrogen, -Chamber, -CO2) %>% rename(Depth_cm = Depth)

SO4_dat <- read.csv(here("..", "GCREW","CO2xN", "Porewater", "Sulfate_Chloride", year, "Compiled_Data", paste0(path, "SO4_Cl_", year,  ".csv"))) %>% mutate(Site = "GCReW", Project ="CO2xN", Community = "SCAM", Nickname = "2-Meter", N_Treatment = ifelse(Nitrogen == 0, "Amended", "Ambient"), CO2_Treatment = ifelse(Treatment == 1 | Treatment == 2, "Ambient", "Elevated"), Plot = sub("-.*", "", SampleID)) %>% select(-Treatment, -SampleID, -Nitrogen, -Chamber, -CO2) %>% rename(SO4_Conc_mM = SO4_mM, Cl_Conc_mM = Cl_mM, Depth_cm = Depth)
  
H2S_dat <-  read.csv(here("..", "GCREW","CO2xN", "Porewater", "Sulfide", year, "Compiled_Data", paste0(path, "H2S_", year, ".csv"))) %>% mutate(Site = "GCReW", Project ="CO2xN", Community = "SCAM", Nickname = "2-Meter", N_Treatment = ifelse(Nitrogen == 0, "Amended", "Ambient"), CO2_Treatment = ifelse(Treatment == 1 | Treatment == 2, "Ambient", "Elevated"), Plot = sub("-.*", "", SampleID)) %>% select(-Treatment, -SampleID, -Nitrogen, -Chamber, -CO2) %>% rename(H2S_Conc_uM = mM_Sulfide, Depth_cm = Depth)






  
```


%>% mutate(Site = "GCReW", Project ="CO2xN", Community = "SCAM", Nickname = "2-Meter", N_Treatment = ifelse(Nitrogen == 0, "Amended", "Ambient"), CO2_Treatment = ifelse(Treatment == 1 | Treatment == 2, "Ambient", "Elevated"), Plot = strsplit(str1, "[-]")[[1]][1], Depthc_cm = strsplit(str1, "[-]")[[2]][1]))


##Select Columns we want
```{r}

#CH4
CH4_sel <- CH4_dat %>% mutate(Month  = ifelse(Month %like% "Sept", "September", Month)) %>% dplyr::select(Site, Project, Year, Month, Community, Nickname, Plot, Depth_cm, CO2_Treatment, N_Treatment, CH4_Conc_uM)

#NH3
NH3_sel <- NH3_dat %>% mutate(Month  = ifelse(Month %like% "Sept", "September", Month)) %>% dplyr::select(Site, Project, Year, Month, Community, Nickname, Plot, Depth_cm, CO2_Treatment, N_Treatment, NH3_Conc_uM)

#pH
pH_sel <- pH_dat %>% mutate(Month  = ifelse(Month %like% "Sept", "September", Month)) %>% dplyr::select(Site, Project, Year, Month, Community, Nickname, Plot, Depth_cm, CO2_Treatment, N_Treatment, pH)

#SO4
SO4_sel <- SO4_dat %>% mutate(Month  = ifelse(Month %like% "Sept", "September", Month)) %>% dplyr::select(Site, Project, Year, Month, Community, Nickname, Plot, Depth_cm, CO2_Treatment, N_Treatment, SO4_Conc_mM, Cl_Conc_mM)

#H2S
H2S_sel <- H2S_dat %>% mutate(Month  = ifelse(Month %like% "Sept", "September", Month)) %>% dplyr::select(Site, Project, Year, Month, Community, Nickname, Plot, Depth_cm, CO2_Treatment, N_Treatment, H2S_Conc_uM)


```

##Join all Analytes
```{r}
CH4_NH3_join <- full_join(CH4_sel, NH3_sel)

CH4_NH3_pH_join <- full_join(CH4_NH3_join, pH_sel)

CH4_NH3_pH_SO4_join <- full_join(CH4_NH3_pH_join, SO4_sel)

All_join <- full_join(CH4_NH3_pH_SO4_join, H2S_sel)
```

##Write Data
```{r}

write.csv(All_join, paste0("CO2xN_Porewater_", year, ".csv"),row.names = FALSE)

```



