---
title: "GC_Collate_Data_CO2xN"
author: "Brenden Blakley"
date: "2025-08-25"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(stringr)
library(purrr)
library(gganimate)
library(gifski)

```

```{r , echo=FALSE}

CH4_processed_files <- c("GCReW_CO2xN_Porewater_CH4_202505.csv","GCReW_CO2xN_Porewater_CH4_202507.csv","GCReW_CO2xN_Porewater_CH4_202509.csv" )
data_CH4 <- map(CH4_processed_files, read.csv)

# Combining Files
df_combo <- bind_rows(data_CH4)

df_combo <- df_combo[,-1]

### Methane 
CH4_forplot <- df_combo

# Mean & SD

CH4_forplot %>% group_by()
```

## Visualize Data
```{r Visualize Data, echo=FALSE}

#ensure points are in correct order

CH4_forplot <- CH4_forplot[order(CH4_forplot$Depth_cm), ]

color1 <- c("L1", "L2", "L3", "L4")
color2 <- c("L5", "L6", "L8", "L10")
color3 <- c("L7", "L9", "L11", "L12")
color4 <- c("L13", "L14", "L16", "L15")
color5 <- c("L17", "L18", "L19", "L20")

CH4_forplot <- CH4_forplot %>%
  mutate(
    Plot_Color = case_when(
      Plot %in% color1 ~ "Color1",
      Plot %in% color2 ~ "Color2",
      Plot %in% color3 ~ "Color3",
      Plot %in% color4 ~ "Color4",
      Plot %in% color5 ~ "Color5"
    )
  ) %>%
  mutate(Treatment = ifelse(
    CO2_Treatment == "Elevated" &
      N_Treatment == "Amended",
    "eCO2 & eN",
    ifelse(
      CO2_Treatment == "Elevated" &
        N_Treatment == "Ambient",
      "eCO2 & aN",
      ifelse(
        CO2_Treatment == "Ambient" &
          N_Treatment == "Amended"  ,
        "aCO2 & eN" ,
        "aCO2 & aN"
      )
    )
  ))  %>%
  mutate(CO2_Treatment = ifelse(CO2_Treatment == "Ambient", "aCO2", "eCO2"))  %>%
  mutate(N_Treatment = ifelse(N_Treatment == "Ambient", "aN", "eN")) %>%
  mutate(Time_ch = paste0(Month, "01", Year)) %>%
  mutate(Time = as.Date(Time_ch, format = "%B%d%Y")) %>%
  arrange(Time, Depth_cm) %>% 
  mutate(Treatment_D = paste0(Treatment, "_", Depth_cm, "_", Month)) %>%
  group_by(Treatment_D) %>% 
  mutate(CH4_mean = mean(CH4_Conc_uM)) %>%
  mutate(CH4_SD = sd(CH4_Conc_uM)) %>%
  ungroup() %>%
  distinct(Treatment_D, .keep_all = TRUE)
#need to work out how best to plot these data
```

```{r Visualize Data, echo=FALSE}

viz_CH4_plot2 <- ggplot(data = CH4_forplot, aes(
  x = factor(as.factor(CO2_Treatment), levels = c("eCO2", "aCO2")),
  y = CH4_mean,
  fill = as.factor(Treatment),
  color = as.factor(Treatment)
)) +
  geom_bar(
    stat = "identity",
    position = position_dodge2(padding = 0.25,preserve = "single")
  ) +
  facet_grid(Depth_cm ~ Month, scales = "fixed") +
  scale_fill_manual(values = c(
    "eCO2 & eN" = "#DB5461",
    "eCO2 & aN" = "#454ADE", 
    "aCO2 & eN" = "white",
    "aCO2 & aN" = "white"
  ),
    name = "Treatment:",
    breaks = c("eCO2 & eN", "eCO2 & aN", "aCO2 & aN", "aCO2 & eN"),
    labels = c("eCO2 & eN", "eCO2 & aN", "aCO2 & aN", "aCO2 & eN")
    
  ) +
  scale_color_manual(values = c(
    "eCO2 & eN" = "#DB5461",
    "eCO2 & aN" = "#454ADE", 
    "aCO2 & eN" = "#DB5461",
    "aCO2 & aN" = "#454ADE"
  ),
    name = "Treatment:",
    breaks = c("eCO2 & eN", "eCO2 & aN", "aCO2 & aN", "aCO2 & eN"),
    labels = c("eCO2 & eN", "eCO2 & aN", "aCO2 & aN", "aCO2 & eN")
  ) +
  theme_classic() +
  labs(x = " ",
       y = "CH4 (uM)",
       title = "CO2xN: Porewater Methane"
       ) +
  theme(legend.position = "right") +
  scale_x_discrete(drop = TRUE) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  ) +
coord_flip()
print(viz_CH4_plot2)

```



```{r, echo=FALSE}
#ensure points are in correct order

#make plot
viz_CH4_plot_2 <- ggplot(data = CH4_forplot, aes(x = CH4_mean, y = Depth_cm)) +
  geom_point(size = 3) +
  geom_path(linewidth = 1) +
  geom_errorbar(aes(xmin = CH4_mean - CH4_SD, xmax = CH4_mean + CH4_SD)) +
  facet_grid(Treatment ~ ., scales = "fixed") +
  labs(
    x = "CH4 (uM)",
    y = "Depth (cm)",
    title = "CO2xN: Porewater CH4 by Treatment {format.Date(closest_state, '%B - %Y')}"
  ) +
  scale_y_reverse(breaks = c(20, 40, 80), limits = c(90, 10)) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.8
    )
  ) + transition_states(Time, transition_length = 4, state_length = 8)+
  ease_aes('linear')

animate(viz_CH4_plot_2, start_pause = 10, renderer = gifski_renderer())
```
# Data Export
```{r}

write.csv(df_combo, "GCReW_CO2xN_Porewater_CH4_2025_ALL.csv")

```

